// flow-typed signature: b6aa2db656d6829f2143d4ada4cdd1ff
// flow-typed version: <<STUB>>/electron-squirrel-startup_v1.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-squirrel-startup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-squirrel-startup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-squirrel-startup/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-squirrel-startup/index' {
  declare module.exports: $Exports<'electron-squirrel-startup'>;
}
declare module 'electron-squirrel-startup/index.js' {
  declare module.exports: $Exports<'electron-squirrel-startup'>;
}
declare module 'electron-squirrel-startup/test/index.test.js' {
  declare module.exports: $Exports<'electron-squirrel-startup/test/index.test'>;
}
