// flow-typed signature: d63b5f97adafe5c101a5239fb60d2c13
// flow-typed version: <<STUB>>/node-binance-api_v0.9.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-binance-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-binance-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-binance-api/async' {
  declare module.exports: any;
}

declare module 'node-binance-api/examples/balances-and-exchangeInfo' {
  declare module.exports: any;
}

declare module 'node-binance-api/examples/example' {
  declare module.exports: any;
}

declare module 'node-binance-api/examples/experiments' {
  declare module.exports: any;
}

declare module 'node-binance-api/examples/fix-timestamp-error' {
  declare module.exports: any;
}

declare module 'node-binance-api/examples/standalone' {
  declare module.exports: any;
}

declare module 'node-binance-api/examples/subscribe-to-all' {
  declare module.exports: any;
}

declare module 'node-binance-api/examples/websocket-ticker' {
  declare module.exports: any;
}

declare module 'node-binance-api/node-binance-api' {
  declare module.exports: any;
}

declare module 'node-binance-api/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-binance-api/async.js' {
  declare module.exports: $Exports<'node-binance-api/async'>;
}
declare module 'node-binance-api/examples/balances-and-exchangeInfo.js' {
  declare module.exports: $Exports<'node-binance-api/examples/balances-and-exchangeInfo'>;
}
declare module 'node-binance-api/examples/example.js' {
  declare module.exports: $Exports<'node-binance-api/examples/example'>;
}
declare module 'node-binance-api/examples/experiments.js' {
  declare module.exports: $Exports<'node-binance-api/examples/experiments'>;
}
declare module 'node-binance-api/examples/fix-timestamp-error.js' {
  declare module.exports: $Exports<'node-binance-api/examples/fix-timestamp-error'>;
}
declare module 'node-binance-api/examples/standalone.js' {
  declare module.exports: $Exports<'node-binance-api/examples/standalone'>;
}
declare module 'node-binance-api/examples/subscribe-to-all.js' {
  declare module.exports: $Exports<'node-binance-api/examples/subscribe-to-all'>;
}
declare module 'node-binance-api/examples/websocket-ticker.js' {
  declare module.exports: $Exports<'node-binance-api/examples/websocket-ticker'>;
}
declare module 'node-binance-api/node-binance-api.js' {
  declare module.exports: $Exports<'node-binance-api/node-binance-api'>;
}
declare module 'node-binance-api/test.js' {
  declare module.exports: $Exports<'node-binance-api/test'>;
}
